services:
  postgres:
    image: postgres:16-alpine
    container_name: mixie-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mixie
    ports:
      - '5432:5432'
    volumes:
      - ./.vols/postgres:/var/lib/postgresql/data # Mount a persistent volume for data

  kafka-1:
    image: bitnami/kafka:latest
    container_name: mixie-kafka
    ports:
      - '9092:9092' # Expose port 9092 to the host
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=WnLkTHhkQaiJbwP8FClPhw
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9090,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - ./.vols/kafka:/bitnami/kafka

  redpanda:
    image: docker.vectorized.io/vectorized/redpanda:latest
    container_name: mixie-redpanda
    environment:
      - REDPANDA_AUTO_CREATE_TOPICS=true
      - REDPANDA_DEVELOPER_MODE=true
    ports:
      - '8081:8081' # Schema Registry port
    command:
      - redpanda start --schema-registry-addr 0.0.0.0:8081
