services:
  postgres:
    image: postgres:16-alpine
    container_name: mixietape-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mixietape
    ports:
      - '5432:5432'
    volumes:
      - ~/docker/postgres/mixietape-postgres:/var/lib/postgresql/data # Mount a persistent volume for data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mixietape-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - '5672:5672' # Port for RabbitMQ connections
      - '15672:15672' # Port for RabbitMQ management UI

  redpanda:
    image: docker.vectorized.io/vectorized/redpanda:latest
    container_name: mixietape-redpanda
    environment:
      - REDPANDA_AUTO_CREATE_TOPICS=true
      - REDPANDA_DEVELOPER_MODE=true
    ports:
      - '8081:8081' # Schema Registry port
    command:
      - redpanda start --schema-registry-addr 0.0.0.0:8081

  # apicurio-registry:
  #   image: apicurio/apicurio-registry-sql:2.2.5.Final
  #   container_name: mixietape-apicurio-registry
  #   environment:
  #     QUARKUS_DATASOURCE_JDBC_URL: 'jdbc:postgresql://postgres:5432/schema_registry'
  #     QUARKUS_DATASOURCE_USERNAME: 'postgres'
  #     QUARKUS_DATASOURCE_PASSWORD: 'postgres'
  #     REGISTRY_DATASOURCE_SCHEMA_CREATE: 'true'
  #     AUTH_ENABLED: 'false'
  #   ports:
  #     - '8888:8080'
  #   depends_on:
  #     - postgres
  # jumpbox:
  #   container_name: jumpbox
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.jumpbox
  #   volumes:
  #     - ./src:/mixietape
  #   working_dir: /mixietape
  #   stdin_open: true
  #   tty: true
